# Due to docker's restrictions (maybe), we cannot do dmoj-autoconf during the build process.
# So I added these in advance. These things will be working on running.

id: ExampleJudge
key: "The_key_you_set_in_admin_paneL"
problem_storage_root:
  - /problems
runtime:
  as_x64: /usr/bin/x86_64-linux-gnu-as
  as_x86: /usr/bin/as
  awk: /usr/bin/mawk
  cat: /bin/cat
  g++: /usr/bin/g++
  g++11: /usr/bin/g++-4.9
  g++14: /usr/bin/g++
  gcc: /usr/bin/gcc
  gcc11: /usr/bin/gcc
  ld_x64: /usr/bin/x86_64-linux-gnu-ld
  ld_x86: /usr/bin/ld
  perl: /usr/bin/perl
  python: /usr/bin/python2.7
  python3: /usr/bin/python3.4
  sed: /bin/sed

